export const dummyHrAllStudentsResponse = [
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uh',
    fullName: 'Jan Kowalski',
    courseDegree: 1,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuhsxccjhbs29u3hd99uhasdds',
    fullName: 'Krzysztof Pawłowski',
    courseDegree: 2,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuhsxccjhbs2sdfs9u3hd99uh',
    fullName: 'Mariusz Lewandowski',
    courseDegree: 3,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuhsljknxccjhbs29u3hd99uh',
    fullName: 'Tomasz Czerwiński',
    courseDegree: 4,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuhsxbv4ccjhbs29u3hd99uh',
    fullName: 'Marcin Łącała',
    courseDegree: 5,
    courseEngagement: 1,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuh45gq12sxccjhbs29u3hd99uh',
    fullName: 'Jan Błaszczyk',
    courseDegree: 5,
    courseEngagement: 2,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
  {
    id: 'qwertyoiuhsxccjhbs29u3hd9ds34v9uh',
    fullName: 'Adrian Majcher',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
  },
];

export const dummyHrAllStudentsInterviewResponse = [
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uah',
    fullName: 'Jan Kowalski',
    courseDegree: 1,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '11.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uhxc',
    fullName: 'Krzysztof Pawłowski',
    courseDegree: 2,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '18.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uhgf',
    fullName: 'Mariusz Lewandowski',
    courseDegree: 3,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '20.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uhtty',
    fullName: 'Tomasz Czerwiński',
    courseDegree: 4,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '21.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99ujhih',
    fullName: 'Marcin Łącała',
    courseDegree: 5,
    courseEngagement: 1,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '22.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99u65tb2h',
    fullName: 'Jan Błaszczyk',
    courseDegree: 5,
    courseEngagement: 2,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '24.07.2020 r.',
  },
  {
    id: 'qwertyoiuhsxccjhbs29au3hd99uhpoi',
    fullName: 'Adrian Majcher',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: '6 miesięcy',
    reservationDate: '25.07.2020 r.',
  },
];
