import { ExpectedContractType, ExpectedWorkType } from 'types';
import { StudentDetails } from '../types/hr/hr';

export const dummyHrAllStudentsResponse: StudentDetails[] = [
  {
    id: 'asdgfgdh',
    firstName: 'Jacek',
    lastName: 'Murański',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '05.08.2022r',
    studentInfoId: '13',
  },
  {
    id: 'asdhfgh',
    firstName: 'Agata',
    lastName: 'Bufalo',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '07.08.2022r',
    studentInfoId: '13',
  },
  {
    id: 'asdqweq',
    firstName: 'Elvis',
    lastName: 'Presley',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '06.08.2022r',
    studentInfoId: '13',
  },
  {
    id: 'asdassdf',
    firstName: 'Franek',
    lastName: 'Kimono',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '08.08.2022r',
    studentInfoId: '13',
  },
  {
    id: 'asdsda',
    firstName: 'Zbyszko',
    lastName: 'Mariacki',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '06.08.2022r',
    studentInfoId: '13',
  },
  {
    id: 'asd',
    firstName: 'Maciek',
    lastName: 'Maciek',
    courseDegree: 5,
    courseEngagement: 3,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: ExpectedWorkType.ON_SITE,
    targetWorkCity: 'Warszawa',
    expectedContractType: ExpectedContractType.EMPLOYMENT,
    expectedSalary: 8000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 0,
    reservationDate: '10.08.2022r',
    studentInfoId: '13',
  },
];
